# Generated by Django 2.2.7 on 2019-11-26 21:23

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('codeCommande', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('dateCreation', models.DateTimeField(default=datetime.datetime.now)),
                ('dateModification', models.DateTimeField(auto_now=True)),
                ('statutCommande', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='HistoryAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modificationType', models.CharField(max_length=64)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('modificationBy', models.CharField(max_length=128)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande', to='AppCommandes.Commande')),
            ],
        ),
    ]
