# Generated by Django 2.2.7 on 2020-11-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCommandes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='categorie',
        ),
    ]
