# Generated by Django 2.2.7 on 2020-11-24 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCommandes', '0002_remove_produit_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerte',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerte', to='AppCommandes.Produit'),
        ),
    ]
