# Generated by Django 2.2.7 on 2019-12-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCommandes', '0002_supportapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportapp',
            name='numSupport',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
