# Generated by Django 2.2.7 on 2019-12-02 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCommandes', '0003_supportapp_numsupport'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=64)),
                ('loginDate', models.DateTimeField(default=datetime.datetime.now)),
                ('ipAddress', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
