# Generated by Django 2.2.7 on 2020-11-23 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCommandes', '0004_historylogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeProblems', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='AlleeMagasin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AlleeReserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('floor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=128)),
                ('codePostal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('stock', models.FloatField()),
                ('alleeMagasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='AppCommandes.AlleeMagasin')),
                ('alleeReserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='AppCommandes.AlleeReserve')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='historyaction',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='supportapp',
            name='versionFront',
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='HistoryAction',
        ),
        migrations.AddField(
            model_name='categorie',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='AppCommandes.Role'),
        ),
        migrations.AddField(
            model_name='alleereserve',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alleereserves', to='AppCommandes.Categorie'),
        ),
        migrations.AddField(
            model_name='alleemagasin',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alleemagasins', to='AppCommandes.Categorie'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='alleeMagasin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerte', to='AppCommandes.AlleeMagasin'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerte', to='AppCommandes.Produit'),
        ),
    ]
